var CANVAS_WIDTH = 900;
var CANVAS_HEIGHT = 1080;

var EDGEBOARD_X = 15;
var EDGEBOARD_Y = 155;

var FPS_TIME      = 1000/24;
var DISABLE_SOUND_MOBILE = true;

var PRIMARY_FONT = "FranklinGothicURW-Hea";
var SECONDARY_FONT = "FranklinGothicURW-Med";

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_DRAG_START  = 4;
var ON_DRAG_END    = 5;
var ON_BUT_YES_DOWN = 6;

var TYPE_STAR = 8;
var TYPE_BOMB = 9;
var TYPE_CLOCK = 10;
var TYPE_CHANGING = 11;

var PARTICLE_OFFSET = new Array();
PARTICLE_OFFSET[0] = {x: 0, y: 81};
PARTICLE_OFFSET[1] = {x: 0, y: 80};
PARTICLE_OFFSET[2] = {x: -1, y: 81};
PARTICLE_OFFSET[3] = {x: 0, y: 80};
PARTICLE_OFFSET[4] = {x: 0, y: 82};
PARTICLE_OFFSET[5] = {x: 0, y: 81};
PARTICLE_OFFSET[6] = {x: 0, y: 81};
PARTICLE_OFFSET[7] = {x: 0, y: 80};
PARTICLE_OFFSET[8] = {x: -5, y: 81};
PARTICLE_OFFSET[9] = {x: 0, y: 0};
PARTICLE_OFFSET[10] = {x: -1, y: 33};
PARTICLE_OFFSET[12] = {x: -8, y: 30};

var CELL_FILL_NULL = 0;
var CELL_FILL_ITEM = 1;
var CELL_FILL_BOMB = 2;
var CELL_FILL_STAR = 3;
var CELL_FILL_BLOCK = 4;
var CELL_FILL_CLOCK = 5;
var CELL_FILL_CHANGE = 6;
var CELL_FILL_STARANDBLOCK = 7;
var CELL_FILL_TRAP = 8;

var CELL_STATE_MATCHED = -1;
var CELL_STATE_DISABLE = -2;
var CELL_STATE_INVISIBLE = -3;

var CHEF_AUDIO_STEP_0 = 0;
var CHEF_AUDIO_STEP_1 = 1;

var CELL_SIZE = 100;
var TIME_FALL = 100;

var MAX_FRUITS_ROT_SPEED = 2;

var SCORES_FOR_SINGLE;
var SCORES_FOR_BOMB;
var EXTRA_ITEM_MULTIPLIER;

var TIMER_HINT;

var TIME_TO_ADD;
var TIME_FOR_QUAD;
var TIME_FOR_QUINT;

var STEP_1_INCREASE_FRUITS;
var STEP_2_INCREASE_FRUITS;
var STEP_3_INCREASE_FRUITS;
var STEP_4_INCREASE_FRUITS;

var STARTING_TIME;
var ENABLE_FULLSCREEN;
var ENABLE_CHECK_ORIENTATION;